export enum LanguageEnum{
    AR = "ar",
    BN = "bn",
    DE = "de",
    EN = "en",
    ES = "es",
    FR = "fr",
    IT = "it",
    JA = "ja",
    KO = "ko",
    PL = "pl",
    PT = "pt",
    RU = "ru",
    ZH_CN = "zh_CN",
    ZH_TW = "zh_TW",
}